[meta]
# site title, show in <title>
title = "ZACH"

# subtitle, words after title, in description
subtitle = "Just For Fun"

# print in html <meta>
keyword = "zach,fun,snakego"

# print in html <meta>
desc = "Snakego is a simple blog"

# build links for feed, sitemap
domain = "snakego.com"

# root path for site# if empty, build as http://{domain}/
root = "http://snakego.com/"

# cover page for homepage
cover = "@media/cover.jpg"

# global language,
# its used in global posts and themes, unless pages set lang
lang = "zh"


[[nav]]
link = "/"
title = "Home"
i18n = "home"
# set nav to active status
hover = "index"
blank = false

[[nav]]
link = "/archive"
title = "Archive"
i18n = "archive"
hover = "archive"

[[nav]]
link = "/about"
title = "About"
i18n = "about"
hover = "about"

[[author]]
name = "zach"
email = "zileyuan@gmail.com"
url = "http://snakego.com"
avatar = "@media/author.png"
bio = "the robot of pugo, who generates all default contents."

# comment settings
# please only set one value
# if multi values, it prints all comment iframes
[comment]
# disqus site name
disqus = ""
# duoshuo short name
duoshuo = ""

# analytics settings
# please only set one value
# if multi values, it prints all analytics codes
[analytics]
# google analytics, need as UA-XXXXX-Y
google = ""
# baidu analytics, need hash-code in hm.js?hash-code
baidu = ""

[build]
# disable_post disable to read & compile post data
disable_post = false
# disable_page disable to read & compile page data
disable_page = false
# post_dir set posts directory
post_dir = "post"
# page_dir set pages directory
page_dir = "page"
# media dir set media directory, based on source directory
media_dir = "media"
